meta_product_name: "Jessica Pring"
meta_title: "Jessica Pring - Full Stack Web Developer"
meta_description: "Hi! My name is Jess and I am a full stack web developer living in London. I am proficient in Ruby, Ruby on Rails, JavaScript, HTML and CSS."
meta_image: "cover.png" # should exist in `app/assets/images/`
